name: Build and Deploy to Release Branch

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    permissions:
      contents: write

    steps:
      - name: Checkout main branch
        uses: actions/checkout@v4

      - name: Setup Bun
        uses: oven-sh/setup-bun@v1

      - name: Install dependencies
        run: bun install

      - name: Build the library
        run: bun run build

      - name: Commit and push code + dist to release
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"

          # Create release branch from current commit
          git checkout -B release

          # Force add the ignored dist folder
          git add -f dist

          # Add all other changes (code, configs, etc.)
          git add -A

          # Commit with same message as main branch
          git commit -m "${{ github.event.head_commit.message }}" || echo "No changes to commit"

          # Push to release (force to overwrite if needed)
          git push origin release --force
